jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: btpbxkt-th59875

      # User/password auth
      user: XXXXXXX
      password: XXXXXXXX

      role: ACCOUNTADMIN
      database: JAFFLE_SHOP
      warehouse: COMPUTE_WH
      schema: dev

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)
